/*
Copyright © 2020 AltoStack <info@altostack.io>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package cmd

import (
	"time"

	"github.com/AltoStack/dynamodump/actions"

	"github.com/spf13/cobra"
)

func init() {
	rootCmd.AddCommand(backupCmd)

	backupCmd.Flags().BoolVarP(&s3DateSuffix, "s3-bucket-folder-name-suffix", "p", false, "Adds an autogenerated suffix folder named using the UTC date in the format YYYY-mm-dd-HH24-MI-SS to the provided S3 folder. Environment variable: DYN_S3_BUCKET_NAME_SUFFIX")
}

var backupCmd = &cobra.Command{
	Use:   "backup",
	Short: "Backup a DynamoDB Table to S3",
	Run: func(cmd *cobra.Command, args []string) {
		actions.TableBackup(dynamoTableName, dynamoBatchSize, time.Duration(waitTime)*time.Millisecond, s3BucketName, s3BucketFolderName, s3DateSuffix, dynamoTableRegion, roleAssumed, s3BucketAccountID, s3BucketRegion)
	},
}
